//
//  Currency.swift
//  Format
//
//  Created by Roy Marmelstein on 15/11/2015.
//  Copyright © 2015 Roy Marmelstein. All rights reserved.
//

import Foundation

/**
 *  Currency formatter
 */
public enum Currency: NumberFormatter {
    case ADP
    case AED
    case AFA
    case AFN
    case ALK
    case ALL
    case AMD
    case ANG
    case AOA
    case AOK
    case AON
    case AOR
    case ARA
    case ARL
    case ARM
    case ARP
    case ARS
    case ATS
    case AUD
    case AWG
    case AZM
    case AZN
    case BAD
    case BAM
    case BAN
    case BBD
    case BDT
    case BEC
    case BEF
    case BEL
    case BGL
    case BGM
    case BGN
    case BGO
    case BHD
    case BIF
    case BMD
    case BND
    case BOB
    case BOL
    case BOP
    case BOV
    case BRB
    case BRC
    case BRE
    case BRL
    case BRN
    case BRR
    case BRZ
    case BSD
    case BTN
    case BUK
    case BWP
    case BYB
    case BYR
    case BZD
    case CAD
    case CDF
    case CHE
    case CHF
    case CHW
    case CLE
    case CLF
    case CLP
    case CNX
    case CNY
    case COP
    case COU
    case CRC
    case CSD
    case CSK
    case CUC
    case CUP
    case CVE
    case CYP
    case CZK
    case DDM
    case DEM
    case DJF
    case DKK
    case DOP
    case DZD
    case ECS
    case ECV
    case EEK
    case EGP
    case EQE
    case ERN
    case ESA
    case ESB
    case ESP
    case ETB
    case EUR
    case FIM
    case FJD
    case FKP
    case FRF
    case GBP
    case GEK
    case GEL
    case GHC
    case GHS
    case GIP
    case GMD
    case GNF
    case GNS
    case GQE
    case GRD
    case GTQ
    case GWE
    case GWP
    case GYD
    case HKD
    case HNL
    case HRD
    case HRK
    case HTG
    case HUF
    case IDR
    case IEP
    case ILP
    case ILR
    case ILS
    case INR
    case IQD
    case IRR
    case ISJ
    case ISK
    case ITL
    case JMD
    case JOD
    case JPY
    case KES
    case KGS
    case KHR
    case KMF
    case KPW
    case KRH
    case KRO
    case KRW
    case KWD
    case KYD
    case KZT
    case LAK
    case LBP
    case LKR
    case LRD
    case LSL
    case LSM
    case LTL
    case LTT
    case LUC
    case LUF
    case LUL
    case LVL
    case LVR
    case LYD
    case MAD
    case MAF
    case MCF
    case MDC
    case MDL
    case MGA
    case MGF
    case MKD
    case MKN
    case MLF
    case MMK
    case MNT
    case MOP
    case MRO
    case MTL
    case MTP
    case MUR
    case MVP
    case MVR
    case MWK
    case MXN
    case MXP
    case MXV
    case MYR
    case MZE
    case MZM
    case MZN
    case NAD
    case NGN
    case NIC
    case NIO
    case NLG
    case NOK
    case NPR
    case NZD
    case OMR
    case PAB
    case PEI
    case PEN
    case PES
    case PGK
    case PHP
    case PKR
    case PLN
    case PLZ
    case PTE
    case PYG
    case QAR
    case RHD
    case ROL
    case RON
    case RSD
    case RUB
    case RUR
    case RWF
    case SAR
    case SBD
    case SCR
    case SDD
    case SDG
    case SDP
    case SEK
    case SGD
    case SHP
    case SIT
    case SKK
    case SLL
    case SOS
    case SRD
    case SRG
    case SSP
    case STD
    case SUR
    case SVC
    case SYP
    case SZL
    case THB
    case TJR
    case TJS
    case TMM
    case TMT
    case TND
    case TOP
    case TPE
    case TRL
    case TRY
    case TTD
    case TWD
    case TZS
    case UAH
    case UAK
    case UGS
    case UGX
    case USD
    case USN
    case USS
    case UYI
    case UYP
    case UYU
    case UZS
    case VEB
    case VEF
    case VND
    case VNN
    case VUV
    case WST
    case XAF
    case XAG
    case XAU
    case XBA
    case XBB
    case XBC
    case XBD
    case XCD
    case XDR
    case XEU
    case XFO
    case XFU
    case XOF
    case XPD
    case XPF
    case XPT
    case XRE
    case XSU
    case XTS
    case XUA
    case XXX
    case YDD
    case YER
    case YUD
    case YUM
    case YUN
    case YUR
    case ZAL
    case ZAR
    case ZMK
    case ZMW
    case ZRN
    case ZRZ
    case ZWL
    case ZWR
    
    /// Modifier
    public var modifier: String {
        switch self {
        case ADP:
            return "ADP"
        case AED:
            return "AED"
        case AFA:
            return "AFA"
        case AFN:
            return "AFN"
        case ALK:
            return "ALK"
        case ALL:
            return "ALL"
        case AMD:
            return "AMD"
        case ANG:
            return "ANG"
        case AOA:
            return "AOA"
        case AOK:
            return "AOK"
        case AON:
            return "AON"
        case AOR:
            return "AOR"
        case ARA:
            return "ARA"
        case ARL:
            return "ARL"
        case ARM:
            return "ARM"
        case ARP:
            return "ARP"
        case ARS:
            return "ARS"
        case ATS:
            return "ATS"
        case AUD:
            return "AUD"
        case AWG:
            return "AWG"
        case AZM:
            return "AZM"
        case AZN:
            return "AZN"
        case BAD:
            return "BAD"
        case BAM:
            return "BAM"
        case BAN:
            return "BAN"
        case BBD:
            return "BBD"
        case BDT:
            return "BDT"
        case BEC:
            return "BEC"
        case BEF:
            return "BEF"
        case BEL:
            return "BEL"
        case BGL:
            return "BGL"
        case BGM:
            return "BGM"
        case BGN:
            return "BGN"
        case BGO:
            return "BGO"
        case BHD:
            return "BHD"
        case BIF:
            return "BIF"
        case BMD:
            return "BMD"
        case BND:
            return "BND"
        case BOB:
            return "BOB"
        case BOL:
            return "BOL"
        case BOP:
            return "BOP"
        case BOV:
            return "BOV"
        case BRB:
            return "BRB"
        case BRC:
            return "BRC"
        case BRE:
            return "BRE"
        case BRL:
            return "BRL"
        case BRN:
            return "BRN"
        case BRR:
            return "BRR"
        case BRZ:
            return "BRZ"
        case BSD:
            return "BSD"
        case BTN:
            return "BTN"
        case BUK:
            return "BUK"
        case BWP:
            return "BWP"
        case BYB:
            return "BYB"
        case BYR:
            return "BYR"
        case BZD:
            return "BZD"
        case CAD:
            return "CAD"
        case CDF:
            return "CDF"
        case CHE:
            return "CHE"
        case CHF:
            return "CHF"
        case CHW:
            return "CHW"
        case CLE:
            return "CLE"
        case CLF:
            return "CLF"
        case CLP:
            return "CLP"
        case CNX:
            return "CNX"
        case CNY:
            return "CNY"
        case COP:
            return "COP"
        case COU:
            return "COU"
        case CRC:
            return "CRC"
        case CSD:
            return "CSD"
        case CSK:
            return "CSK"
        case CUC:
            return "CUC"
        case CUP:
            return "CUP"
        case CVE:
            return "CVE"
        case CYP:
            return "CYP"
        case CZK:
            return "CZK"
        case DDM:
            return "DDM"
        case DEM:
            return "DEM"
        case DJF:
            return "DJF"
        case DKK:
            return "DKK"
        case DOP:
            return "DOP"
        case DZD:
            return "DZD"
        case ECS:
            return "ECS"
        case ECV:
            return "ECV"
        case EEK:
            return "EEK"
        case EGP:
            return "EGP"
        case EQE:
            return "EQE"
        case ERN:
            return "ERN"
        case ESA:
            return "ESA"
        case ESB:
            return "ESB"
        case ESP:
            return "ESP"
        case ETB:
            return "ETB"
        case EUR:
            return "EUR"
        case FIM:
            return "FIM"
        case FJD:
            return "FJD"
        case FKP:
            return "FKP"
        case FRF:
            return "FRF"
        case GBP:
            return "GBP"
        case GEK:
            return "GEK"
        case GEL:
            return "GEL"
        case GHC:
            return "GHC"
        case GHS:
            return "GHS"
        case GIP:
            return "GIP"
        case GMD:
            return "GMD"
        case GNF:
            return "GNF"
        case GNS:
            return "GNS"
        case GQE:
            return "GQE"
        case GRD:
            return "GRD"
        case GTQ:
            return "GTQ"
        case GWE:
            return "GWE"
        case GWP:
            return "GWP"
        case GYD:
            return "GYD"
        case HKD:
            return "HKD"
        case HNL:
            return "HNL"
        case HRD:
            return "HRD"
        case HRK:
            return "HRK"
        case HTG:
            return "HTG"
        case HUF:
            return "HUF"
        case IDR:
            return "IDR"
        case IEP:
            return "IEP"
        case ILP:
            return "ILP"
        case ILR:
            return "ILR"
        case ILS:
            return "ILS"
        case INR:
            return "INR"
        case IQD:
            return "IQD"
        case IRR:
            return "IRR"
        case ISJ:
            return "ISJ"
        case ISK:
            return "ISK"
        case ITL:
            return "ITL"
        case JMD:
            return "JMD"
        case JOD:
            return "JOD"
        case JPY:
            return "JPY"
        case KES:
            return "KES"
        case KGS:
            return "KGS"
        case KHR:
            return "KHR"
        case KMF:
            return "KMF"
        case KPW:
            return "KPW"
        case KRH:
            return "KRH"
        case KRO:
            return "KRO"
        case KRW:
            return "KRW"
        case KWD:
            return "KWD"
        case KYD:
            return "KYD"
        case KZT:
            return "KZT"
        case LAK:
            return "LAK"
        case LBP:
            return "LBP"
        case LKR:
            return "LKR"
        case LRD:
            return "LRD"
        case LSL:
            return "LSL"
        case LSM:
            return "LSM"
        case LTL:
            return "LTL"
        case LTT:
            return "LTT"
        case LUC:
            return "LUC"
        case LUF:
            return "LUF"
        case LUL:
            return "LUL"
        case LVL:
            return "LVL"
        case LVR:
            return "LVR"
        case LYD:
            return "LYD"
        case MAD:
            return "MAD"
        case MAF:
            return "MAF"
        case MCF:
            return "MCF"
        case MDC:
            return "MDC"
        case MDL:
            return "MDL"
        case MGA:
            return "MGA"
        case MGF:
            return "MGF"
        case MKD:
            return "MKD"
        case MKN:
            return "MKN"
        case MLF:
            return "MLF"
        case MMK:
            return "MMK"
        case MNT:
            return "MNT"
        case MOP:
            return "MOP"
        case MRO:
            return "MRO"
        case MTL:
            return "MTL"
        case MTP:
            return "MTP"
        case MUR:
            return "MUR"
        case MVP:
            return "MVP"
        case MVR:
            return "MVR"
        case MWK: 
            return "MWK"
        case MXN: 
            return "MXN"
        case MXP: 
            return "MXP"
        case MXV: 
            return "MXV"
        case MYR: 
            return "MYR"
        case MZE: 
            return "MZE"
        case MZM: 
            return "MZM"
        case MZN: 
            return "MZN"
        case NAD: 
            return "NAD"
        case NGN: 
            return "NGN"
        case NIC: 
            return "NIC"
        case NIO: 
            return "NIO"
        case NLG: 
            return "NLG"
        case NOK: 
            return "NOK"
        case NPR: 
            return "NPR"
        case NZD: 
            return "NZD"
        case OMR: 
            return "OMR"
        case PAB: 
            return "PAB"
        case PEI: 
            return "PEI"
        case PEN: 
            return "PEN"
        case PES: 
            return "PES"
        case PGK: 
            return "PGK"
        case PHP: 
            return "PHP"
        case PKR: 
            return "PKR"
        case PLN: 
            return "PLN"
        case PLZ: 
            return "PLZ"
        case PTE: 
            return "PTE"
        case PYG: 
            return "PYG"
        case QAR: 
            return "QAR"
        case RHD: 
            return "RHD"
        case ROL: 
            return "ROL"
        case RON: 
            return "RON"
        case RSD: 
            return "RSD"
        case RUB: 
            return "RUB"
        case RUR: 
            return "RUR"
        case RWF: 
            return "RWF"
        case SAR: 
            return "SAR"
        case SBD: 
            return "SBD"
        case SCR: 
            return "SCR"
        case SDD: 
            return "SDD"
        case SDG: 
            return "SDG"
        case SDP: 
            return "SDP"
        case SEK: 
            return "SEK"
        case SGD: 
            return "SGD"
        case SHP: 
            return "SHP"
        case SIT: 
            return "SIT"
        case SKK: 
            return "SKK"
        case SLL: 
            return "SLL"
        case SOS: 
            return "SOS"
        case SRD: 
            return "SRD"
        case SRG: 
            return "SRG"
        case SSP: 
            return "SSP"
        case STD: 
            return "STD"
        case SUR: 
            return "SUR"
        case SVC: 
            return "SVC"
        case SYP: 
            return "SYP"
        case SZL: 
            return "SZL"
        case THB: 
            return "THB"
        case TJR: 
            return "TJR"
        case TJS: 
            return "TJS"
        case TMM: 
            return "TMM"
        case TMT: 
            return "TMT"
        case TND: 
            return "TND"
        case TOP: 
            return "TOP"
        case TPE: 
            return "TPE"
        case TRL: 
            return "TRL"
        case TRY: 
            return "TRY"
        case TTD: 
            return "TTD"
        case TWD: 
            return "TWD"
        case TZS: 
            return "TZS"
        case UAH: 
            return "UAH"
        case UAK: 
            return "UAK"
        case UGS: 
            return "UGS"
        case UGX: 
            return "UGX"
        case USD: 
            return "USD"
        case USN: 
            return "USN"
        case USS: 
            return "USS"
        case UYI: 
            return "UYI"
        case UYP: 
            return "UYP"
        case UYU: 
            return "UYU"
        case UZS: 
            return "UZS"
        case VEB: 
            return "VEB"
        case VEF: 
            return "VEF"
        case VND: 
            return "VND"
        case VNN: 
            return "VNN"
        case VUV: 
            return "VUV"
        case WST: 
            return "WST"
        case XAF: 
            return "XAF"
        case XAG: 
            return "XAG"
        case XAU: 
            return "XAU"
        case XBA: 
            return "XBA"
        case XBB: 
            return "XBB"
        case XBC: 
            return "XBC"
        case XBD: 
            return "XBD"
        case XCD: 
            return "XCD"
        case XDR: 
            return "XDR"
        case XEU: 
            return "XEU"
        case XFO: 
            return "XFO"
        case XFU: 
            return "XFU"
        case XOF: 
            return "XOF"
        case XPD: 
            return "XPD"
        case XPF: 
            return "XPF"
        case XPT: 
            return "XPT"
        case XRE: 
            return "XRE"
        case XSU: 
            return "XSU"
        case XTS: 
            return "XTS"
        case XUA: 
            return "XUA"
        case XXX: 
            return "XXX"
        case YDD: 
            return "YDD"
        case YER: 
            return "YER"
        case YUD: 
            return "YUD"
        case YUM: 
            return "YUM"
        case YUN: 
            return "YUN"
        case YUR: 
            return "YUR"
        case ZAL: 
            return "ZAL"
        case ZAR: 
            return "ZAR"
        case ZMK: 
            return "ZMK"
        case ZMW: 
            return "ZMW"
        case ZRN: 
            return "ZRN"
        case ZRZ: 
            return "ZRZ"
        case ZWL: 
            return "ZWL"
        case ZWR: 
            return "ZWR"
        }
    }
    
    /// Type enum
    public var type: NumberFormatterType {
        return NumberFormatterType.Currency
    }
    
    /// NSNumberFormatter style
    public var style: NSNumberFormatterStyle? {
        return NSNumberFormatterStyle.CurrencyStyle
    }

}