source 'https://github.com/CocoaPods/Specs.git'
platform :ios, “9.0”
use_frameworks!

target 'Sample' do
  use_frameworks!

  # Pods for Sample
	pod ‘Format’, :path => '../..'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
